services:
  postgres-db:
    image: postgres:15.7
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_DB: ${PG_DB:-smartshop}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-duong}
    ports: 
      - '5430:5432'
    expose:
      - 5432

  backend:
    build:
      context: ../smartshop-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment: 
      - DB_HOST=${DB_HOST:-postgres-db}
      - DB_PORT=${DB_PORT:-5432}
      # - DB_HOST=host.docker.internal
    ports:
      - 3126:3124
    expose:
      - 3124

  frontend:
    build: 
      context: ../smartshop-frontend
      dockerfile: Dockerfile
    # image: nginx:1.23.3
    ports:
      - 80:80
    # volumes:
    #   - ../smartshop-frontend/build:/usr/share/nginx/html
    #   - ./default.conf:/etc/nginx/conf.d/default.conf

# docker compose run -e DB_HOST=postgres-db -p smartshop up -d